# default values
all:
  sf_guard_plugin:
    profile_class:                UserProfile
    profile_field_name:           sf_guard_user_id
    remember_key_expiration_age:  2592000   # 30 days in seconds
    remember_cookie_name:         codeRepositoryRememberMe   
  lucene:
    per_page: 1
  .array:
    languages:
      c: C
      cpp: C++
      html: HTML
      java: Java
      php: PHP
      ruby: Ruby
      sql: SQL
      xml: XML
  preference:
    box_language_cloud: inline
    box_tag_cloud: inline
    box_snippets: inline
    box_snippets_size: 10
    box_user: inline
    search_size: 10
  isicsSitemapXML:
    modules:       [snippet, tag, language]