# This stipulates the mailer program to be used to send mails, 
# and deactivates the sending of mails in the development 
# environment - the emails in the test data are fake anyway.
dev:
  deliver:    on

all:
  mailer:     smtp
  hostname:   mail.sis-nav.com
  username:   umut.utkan@sistemas.com.tr
  password:   gahve123
  port:       25