set_preference:
  url:   /setPreference/:pname
  param: { module: user, action: setPreference }

popup:
  url:   /popup/:content
  param: { module: site, action: index }

language_list:
  url: /language
  param: { module: language, action: list }

language:
  url: /language/:language
  param: { module: language, action: show }

tag_auto:
  url: /tag/autocomplete
  param: { module: tag, action: autocomplete }
  
tag_list:
  url: /tag/list
  param: { module: tag, action: list }

tag:
  url: /tag/:tag
  param: { module: tag, action: show }

# default rules
homepage:
  url:   /
  param: { module: home, action: main }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }  