default:
  http_metas:
    content-type: text/html

  metas:
    title:        Hoydaa Snippets
    robots:       index, follow
    description:  Snippets is a community website to share your codesnippets.
    keywords:     snippet, hoydaa, highlight
    language:     en

  stylesheets:    [commons, main]

  javascripts:    [util]

  has_layout:     on
  layout:         layout
  
  components:
    sidebar:      [sidebar, default]