default:
  http_metas:
    content-type: text/html

  metas:
    title:        Hoydaa Snippets
    robots:       index, follow
    description:  Hoydaa Snippet Repository
    keywords:     snippet, hoydaa, highlight
    language:     en

  stylesheets:    [main, text, lang-java]

  javascripts:    [util]

  has_layout:     on
  layout:         layout
  
  components:
    sidebar:      [sidebar, default]