default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [newlayout, newmain, sidebox, form, corner]

  javascripts:    [util.js, jquery-1.2.3.js, jquery.corner.js]

  has_layout:     on
  layout:         layout
  
  components:
    sidebar:      [sidebar, default]
