viewAccount:
  is_secure: on

editAccount:
  is_secure: on

changeEmail:
  is_secure: on

changePassword:
  is_secure: on

editProfile:
  is_secure: on
  
listFeeds:
  is_secure: on
  
deleteFeed:
  is_secure: on
  
addFeed:
  is_secure: on
  
savePreferences:
  is_secure: on