propel:
  snippets_snippet:
    _attributes:            { phpName: Snippet }
    id:                     ~
    user_id:                { type: integer, foreignTable: sf_guard_user, foreignReference: id, onDelete: restrict }
    name:                   { type: varchar, size: 255, required: false }
    email:                  { type: varchar, size: 255, required: false }
    title:                  { type: varchar, size: 255 }
    raw_body:               { type: longvarchar, required: true }
    body:                   { type: longvarchar, required: true }
    average_rating:         { type: decimal, size: 4, scale: 2, required: true, default: 0.0 }
    managed_content:        { type: boolean, required: true, default: 0 }
    summary:                { type: longvarchar }
    created_at:             ~
    updated_at:             ~

  snippets_snippet_language:
    _attributes:            { phpName: SnippetLanguage }
    id:                     ~
    snippet_id:             { type: integer, required: true, foreignTable: snippets_snippet, foreignReference: id, onDelete: cascade }
    name:                   { type: varchar, size: 16, required: true }

  snippets_snippet_tag:
    _attributes:            { phpName: Tag }
    snippet_id:             { type: integer, required: true, primaryKey: true, foreignTable: snippets_snippet, foreignReference: id, onDelete: cascade }
    name:                   { type: varchar, size: 100, required: true, primaryKey: true }
    created_at:             ~

  snippets_snippet_comment:
    _attributes:            { phpName: Comment }
    id:                     ~
    snippet_id:             { type: integer, required: true, foreignTable: snippets_snippet, foreignReference: id, onDelete: cascade }
    user_id:                { type: integer, required: false, foreignTable: sf_guard_user, foreignReference: id, onDelete: restrict }
    name:                   { type: varchar, size: 255, required: false }
    email:                  { type: varchar, size: 255, required: false }
    raw_body:               { type: longvarchar, required: true }
    body:                   { type: longvarchar, required: true }
    summary:                { type: varchar, size: 200, required: true }
    created_at:             ~

  # will be improved
  snippets_user_profile:
    _attributes:            { phpName: UserProfile }
    id:                     ~
    user_id:                { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    email:                  { type: varchar, size: 255, required: true }
    first_name:             { type: varchar, size: 255, required: true }
    last_name:              { type: varchar, size: 255, required: true }
    confirmation:           { type: varchar, size: 32 }
    gender:                 { type: char, size: 1, required: false }
    birthday:               { type: date, required: false }

  snippets_user_preference:
    _attributes:            { phpName: Preference }
    id:                     ~
    user_id:                { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    name:                   { type: varchar, size: 255, required: true }
    value:                  { type: varchar, size: 255, required: true }
    
  snippets_user_feed:
    _attributes:            { phpName: UserFeed }
    id:                     ~
    user_id:                { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    query:                  { type: varchar, size: 255, required: true }