MyIndex:
  models:
    Snippet:
      fields:
        id: unindexed
        userid: unindexed
        contributor: text
        title:
          boost: 1.5
          type: text
        strippedTitle: unindexed
        body:
          type: unstored
          transform: strip_tags
        tag: text
        languages: text
        mc: keyword
        summary: unindexed
        createdat: text
      title: title
      description: description
      route: snippet/show?id=%id%
      partial: snippet/searchResult

  index:
    encoding: UTF-8