popupSuccess:
  stylesheets: [-main, popup]
  javascripts: [-util]
  layout: popup

indexSuccess:
  stylesheets: [code-java, code-php, code-c]

highlightSuccess:
  stylesheets: [-main, -commons, code-java, code-php, code-c]
  javascripts: [-util]
  layout: popup