popupSuccess:
  stylesheets: [-main, popup]
  javascripts: [-util]
  layout: popup

indexSuccess:
  stylesheets: [code-java, code-php, code-c, code-python]

highlightSuccess:
  stylesheets: [-main, -commons, code-java, code-php, code-c, code-python]
  javascripts: [-util]
  layout: popup